export const TRANSLATIONS = {
  English: {
    find_jobs: "Find Jobs",
    popular_categories: "Popular Categories",
    latest_jobs: "Latest Jobs",
    search_placeholder: "Search jobs...",
    location: "Location",
    job_type: "Job Type",
    salary: "Salary",
    last_date: "Last Date",
    apply_now: "Apply Now",
    qualification: "Qualification",
    experience: "Experience",
    description: "Description",
    profile: "Profile",
    settings: "Settings",
    language: "Language",
    notifications: "Notifications",
    about: "About",
    logout: "Logout",
    sign_out: "Sign Out",
    edit_profile: "Edit Profile",
    saved_jobs: "Saved Jobs",
    no_saved_jobs: "No saved jobs found.",
    pro_features: "Get Pro Features",
    unlock_pro: "Unlock Pro",
    chat_with_umma: "Chat with Umma AI",
    expired: "Expired",
    active: "Active",
    today: "Today",
    saved: "Saved",
    account_settings: "Account Settings",
    job_preferences: "Job Preferences",
    hiring_partner: "Company Portal (Hire Talent)",
    privacy_visibility: "Privacy & Visibility",
    app_settings: "App Settings",
    support_about: "Support & About",
    membership_management: "Membership Management",
  },
  Hindi: {
    find_jobs: "नौकरियां खोजें",
    popular_categories: "लोकप्रिय श्रेणियां",
    latest_jobs: "नवीनतम नौकरियां",
    search_placeholder: "नौकरियां खोजें...",
    location: "स्थान",
    job_type: "कार्य प्रकार",
    salary: "वेतन",
    last_date: "अंतिम तिथि",
    apply_now: "अभी आवेदन करें",
    qualification: "योग्यता",
    experience: "अनुभव",
    description: "विवरण",
    profile: "प्रोफ़ाइल",
    settings: "सेटिंग्स",
    language: "भाषा",
    notifications: "सूचनाएं",
    about: "के बारे में",
    logout: "लॉगआउट",
    sign_out: "साइन आउट",
    edit_profile: "प्रोफ़ाइल संपादित करें",
    saved_jobs: "सहेजी गई नौकरियां",
    no_saved_jobs: "कोई सहेजी गई नौकरियां नहीं मिलीं।",
    pro_features: "प्रो विशेषताएं प्राप्त करें",
    unlock_pro: "प्रो अनलॉक करें",
    chat_with_umma: "उम्मा AI के साथ चैट करें",
    expired: "समाप्त",
    active: "सक्रिय",
    today: "आज",
    saved: "सहेजा गया",
    account_settings: "अकाउंट सेटिंग्स",
    job_preferences: "नौकरी की प्राथमिकताएं",
    hiring_partner: "कंपनी पोर्टल (हायरिंग शुरू करें)",
    privacy_visibility: "गोपनीयता और दृश्यता",
    app_settings: "ऐप सेटिंग्स",
    support_about: "सहायता और बारे में",
    membership_management: "सदस्यता प्रबंधन",
  },
  Bengali: {
    find_jobs: "চাকরি খুঁজুন",
    popular_categories: "জনপ্রিয় বিভাগ",
    latest_jobs: "সাম্প্রতিক চাকরি",
    search_placeholder: "চাকরি খুঁজুন...",
    location: "অবস্থান",
    job_type: "চাকরির ধরণ",
    salary: "বেতন",
    last_date: "শেষ তারিখ",
    apply_now: "এখনই আবেদন করুন",
    qualification: "যোগ্যতা",
    experience: "অভিজ্ঞতা",
    description: "বর্ণনা",
    profile: "প্রোফাইল",
    settings: "সেটিংস",
    language: "ভাষা",
    notifications: "বিজ্ঞপ্তি",
    about: "সম্পর্কে",
    logout: "লগআউট",
    sign_out: "সাইন আউট",
    edit_profile: "প্রোফাইল সম্পাদনা করুন",
    saved_jobs: "সংরক্ষিত চাকরি",
    no_saved_jobs: "কোন সংরক্ষিত চাকরি পাওয়া যায়নি।",
    pro_features: "প্রো ফিচার পান",
    unlock_pro: "প্রো আনলক করুন",
    chat_with_umma: "উম্মা AI এর সাথে চ্যাট করুন",
    expired: "মেয়াদোত্তীর্ণ",
    active: "সক্রিয়",
    today: "আজ",
    saved: "সংরক্ষিত",
    account_settings: "অ্যাকাউন্ট সেটিংস",
    job_preferences: "চাকরির পছন্দ",
    hiring_partner: "কোম্পানি পোর্টাল (চাকরি পোস্ট করুন)",
    privacy_visibility: "গোপনীয়তা এবং দৃশ্যমানতা",
    app_settings: "অ্যাপ সেটিংস",
    support_about: "সহায়তা এবং সম্পর্কে",
    membership_management: "সদস্যপদ ব্যবস্থাপনা",
  },
  Telugu: {
    find_jobs: "ఉద్యోగాలను కనుగొనండి",
    popular_categories: "ప్రసిద్ధ వర్గాలు",
    latest_jobs: "తాజా ఉద్యోగాలు",
    search_placeholder: "ఉద్యోగాల కోసం వెతకండి...",
    location: "ప్రదేశం",
    job_type: "ఉద్యోగ రకం",
    salary: "జీతం",
    last_date: "చివరి తేదీ",
    apply_now: "ఇప్పుడే దరఖాస్తు చేసుకోండి",
    qualification: "అర్హత",
    experience: "అనుభవం",
    description: "వివరణ",
    profile: "ప్రొఫైల్",
    settings: "సెట్టింగ్‌లు",
    language: "భాష",
    notifications: "నోటిఫికేషన్‌లు",
    about: "గురించి",
    logout: "లాగ్ అవుట్",
    sign_out: "సైన్ అవుట్",
    edit_profile: "ప్రొఫైల్‌ను సవరించండి",
    saved_jobs: "సేవ్ చేసిన ఉద్యోగాలు",
    no_saved_jobs: "సేవ్ చేసిన ఉద్యోగాలేవీ లేవు.",
    pro_features: "ప్రో ఫీచర్లను పొందండి",
    unlock_pro: "ప్రో అన్‌లాక్ చేయండి",
    chat_with_umma: "ఉమ్మ AI తో చాట్ చేయండి",
    expired: "ముగిసింది",
    active: "క్రియాశీల",
    today: "నేడు",
    saved: "సేవ్ చేయబడింది",
    account_settings: "ఖాతా సెట్టింగ్‌లు",
    job_preferences: "ఉద్యోగ ప్రాధాన్యతలు",
    hiring_partner: "కంపెనీ పోర్టల్ (ఉద్యోగాలను పోస్ట్ చేయండి)",
    privacy_visibility: "గోప్యత మరియు దృశ్యమానత",
    app_settings: "యాప్ సెట్టింగ్‌లు",
    support_about: "మద్దతు మరియు గురించి",
    membership_management: "సభ్యత్వ నిర్వహణ",
  },
  Tamil: {
    find_jobs: "வேலைகளைத் தேடுங்கள்",
    popular_categories: "பிரபலமான பிரிவுகள்",
    latest_jobs: "சமீபத்திய வேலைகள்",
    search_placeholder: "வேலைகளைத் தேடுங்கள்...",
    location: "இடம்",
    job_type: "வேலை வகை",
    salary: "சம்பளம்",
    last_date: "கடைசி தேதி",
    apply_now: "இப்போதே விண்ணப்பிக்கவும்",
    qualification: "தகுதி",
    experience: "அனுபவம்",
    description: "விளக்கம்",
    profile: "சுயவிவரம்",
    settings: "அமைப்புகள்",
    language: "மொழி",
    notifications: "அறிவிப்புகள்",
    about: "பற்றி",
    logout: "வெளியேறு",
    sign_out: "வெளியேறு",
    edit_profile: "சுயவிவரத்தைத் திருத்தவும்",
    saved_jobs: "சேமிக்கப்பட்ட வேலைகள்",
    no_saved_jobs: "சேமிக்கப்பட்ட வேலைகள் எதுவும் இல்லை.",
    pro_features: "புரோ அம்சங்களைப் பெறுங்கள்",
    unlock_pro: "புரோவைத் திறக்கவும்",
    chat_with_umma: "உம்மா AI உடன் அரட்டையடிக்கவும்",
    expired: "காலாவதியானது",
    active: "செயலில் உள்ளது",
    today: "இன்று",
    saved: "சேமிக்கப்பட்டது",
    account_settings: "கணக்கு அமைப்புகள்",
    job_preferences: "வேலை விருப்பங்கள்",
    hiring_partner: "நிறுவன போர்டல் (வேலை வாய்ப்பு வெளியிடு)",
    privacy_visibility: "தனியுரிமை மற்றும் தெரிவுநிலை",
    app_settings: "பயன்பாட்டு அமைப்புகள்",
    support_about: "ஆதரவு மற்றும் பற்றி",
    membership_management: "உறுப்பினர் மேலாண்மை",
  },
  Marathi: {
    find_jobs: "नोकर्‍या शोधा",
    popular_categories: "लोकप्रिय श्रेणी",
    latest_jobs: "नवीनतम नोकर्‍या",
    search_placeholder: "नोकर्‍या शोधा...",
    location: "स्थान",
    job_type: "नोकरीचा प्रकार",
    salary: "पगार",
    last_date: "अंतिम तारीख",
    apply_now: "आत्ताच अर्ज करा",
    qualification: "पात्रता",
    experience: "अनुभव",
    description: "वर्णन",
    profile: "प्रोफाइल",
    settings: "सेटिंग्ज",
    language: "भाषा",
    notifications: "अधिसूचना",
    about: "बद्दल",
    logout: "लॉगआउट",
    sign_out: "साइन आउट",
    edit_profile: "प्रोफाइल संपादित करा",
    saved_jobs: "जतन केलेल्या नोकर्‍या",
    no_saved_jobs: "जतन केलेल्या कोणत्याही नोकर्‍या आढळल्या नाहीत.",
    pro_features: "प्रो वैशिष्ट्ये मिळवा",
    unlock_pro: "प्रो अनलॉक करा",
    chat_with_umma: "उम्मा AI सह चॅट करा",
    expired: "कालबाह्य",
    active: "सक्रिय",
    today: "आज",
    saved: "जतन केले",
    account_settings: "खाते सेटिंग्ज",
    job_preferences: "नोकरीची पसंती",
    hiring_partner: "कंपनी पोर्टल (भरती सुरू करा)",
    privacy_visibility: "गोपनीयता आणि दृश्यमानता",
    app_settings: "अ‍ॅप सेटिंग्ज",
    support_about: "मदत आणि बद्दल",
    membership_management: "सदस्यता व्यवस्थापन",
  },
  Gujarati: {
    find_jobs: "નોકરીઓ શોધો",
    popular_categories: "લોકપ્રિય શ્રેણીઓ",
    latest_jobs: "નવીનતમ નોકરીઓ",
    search_placeholder: "નોકરીઓ શોધો...",
    location: "સ્થળ",
    job_type: "નોકરીનો પ્રકાર",
    salary: "પગાર",
    last_date: "અંતિમ તારીખ",
    apply_now: "અત્યારે જ અરજી કરો",
    qualification: "લાયકાત",
    experience: "અનુભવ",
    description: "વર્ણન",
    profile: "પ્રોફાઇલ",
    settings: "સેટિંગ્સ",
    language: "ભાષા",
    notifications: "સૂચનાઓ",
    about: "વિશે",
    logout: "લોગઆઉટ",
    sign_out: "સાઇન આઉટ",
    edit_profile: "પ્રોફાઇલ સંપાદિત કરો",
    saved_jobs: "સાચવેલી નોકરીઓ",
    no_saved_jobs: "કોઈ સાચવેલી નોકરીઓ મળી નથી.",
    pro_features: "પ્રો ફીચર્સ મેળવો",
    unlock_pro: "પ્રો અનલૉક કરો",
    chat_with_umma: "ઉમ્મા AI સાથે ચેટ કરો",
    expired: "સમાપ્ત",
    active: "સક્રિય",
    today: "આજે",
    saved: "સાચવેલ",
    account_settings: "ખાતા સેટિંગ્સ",
    job_preferences: "નોકરીની પસંદગી",
    hiring_partner: "કંપની પોર્ટલ (ભરતી શરૂ કરો)",
    privacy_visibility: "ગોપનીયતા અને દૃશ્યતા",
    app_settings: "એપ્લિકેશન સેટિંગ્સ",
    support_about: "સપોર્ટ અને વિશે",
    membership_management: "સભ્યપદ વ્યવસ્થાપન",
  },
  Kannada: {
    find_jobs: "ಉದ್ಯೋಗಗಳನ್ನು ಹುಡುಕಿ",
    popular_categories: "ಜನಪ್ರಿಯ ವರ್ಗಗಳು",
    latest_jobs: "ಇತ್ತೀಚಿನ ಉದ್ಯೋಗಗಳು",
    search_placeholder: "ಉದ್ಯೋಗಗಳಿಗಾಗಿ ಹುಡುಕಿ...",
    location: "ಸ್ಥಳ",
    job_type: "ಉದ್ಯೋಗದ ವಿಧ",
    salary: "ಸಂಬಳ",
    last_date: "ಕೊನೆಯ ದಿನಾಂಕ",
    apply_now: "ಈಗಲೇ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ",
    qualification: "ಅರ್ಹತೆ",
    experience: "ಅನುಭವ",
    description: "ವಿವರಣೆ",
    profile: "ಪ್ರೊಫೈಲ್",
    settings: "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
    language: "ಭಾಷೆ",
    notifications: "ಅಧಿಸೂಚನೆಗಳು",
    about: "ಬಗ್ಗೆ",
    logout: "ಲಾಗ್ ಔಟ್",
    sign_out: "ಸೈನ್ ಔಟ್",
    edit_profile: "ಪ್ರೊಫೈಲ್ ಸಂಪಾದಿಸಿ",
    saved_jobs: "ಉಳಿಸಲಾದ ಉದ್ಯೋಗಗಳು",
    no_saved_jobs: "ಉಳಿಸಲಾದ ಯಾವುದೇ ಉದ್ಯೋಗಗಳು ಕಂಡುಬಂದಿಲ್ಲ.",
    pro_features: "ಪ್ರೊ ವೈಶಿಷ್ಟ್ಯಗಳನ್ನು ಪಡೆಯಿರಿ",
    unlock_pro: "ಪ್ರೊ ಅನ್ಲಾಕ್ ಮಾಡಿ",
    chat_with_umma: "ಉಮ್ಮ AI ನೊಂದಿಗೆ ಚಾಟ್ ಮಾಡಿ",
    expired: "ಅವಧಿ ಮುಗಿದಿದೆ",
    active: "ಸಕ್ರಿಯ",
    today: "ಇಂದು",
    saved: "ಉಳಿಸಲಾಗಿದೆ",
    account_settings: "ಖಾತೆ ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
    job_preferences: "ಉದ್ಯೋಗ ಆದ್ಯತೆಗಳು",
    hiring_partner: "ಕಂಪನಿ ಪೋರ್ಟಲ್ (ನೇಮಕಾತಿ ಪ್ರಾರಂಭಿಸಿ)",
    privacy_visibility: "ಗೌಪ್ಯತೆ ಮತ್ತು ಗೋಚರತೆ",
    app_settings: "ಅಪ್ಲಿಕೇಶನ್ ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
    support_about: "ಬೆಂಬಲ ಮತ್ತು ಬಗ್ಗೆ",
    membership_management: "ಸದಸ್ಯತ್ವ ನಿರ್ವಹಣೆ",
  },
};

export type TranslationKey = keyof typeof TRANSLATIONS.English;

export const useTranslation = (lang: string) => {
  const t = (key: TranslationKey | string) => {
    const currentLang = (TRANSLATIONS as any)[lang] || TRANSLATIONS.English;
    return currentLang[key] || (TRANSLATIONS.English as any)[key] || key;
  };

  return { t };
};
