name: 24x7 Automatic Job Scout Engine

on:
  schedule:
    - cron: '0 * * * *'  # Har 1 ghante mein automatic chalega
  workflow_dispatch:      # Isse aap jab chahein manually ek click mein chala sakte hain

jobs:
  run-scout:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        pip install firebase-admin requests

    - name: Run Job Scout Script
      env:
        FIREBASE_SECRET_KEY: ${{ secrets.FIREBASE_SECRET_KEY }}
        FIREBASE_DB_URL: "https://job-india-55dd2-default-rtdb.firebaseio.com/" # <-- Apna Realtime DB URL yahan likhein
      run: python fetch_jobs.py
